import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import time
import re

data = pd.read_csv('Airline_review.csv')

data = data.dropna(subset=['Aircraft', 'Type Of Traveller', 'Seat Type', 'Route', 'Date Flown'])
#Imputing missing values for specific columns with the average grouped by airline name and seat type
data[['Seat Comfort', 'Cabin Staff Service', 'Food & Beverages', 'Ground Service', 'Inflight Entertainment', 'Wifi & Connectivity']] = data.groupby(['Airline Name', 'Seat Type'])[['Seat Comfort', 'Cabin Staff Service', 'Food & Beverages', 'Ground Service', 'Inflight Entertainment', 'Wifi & Connectivity']].transform(lambda x: x.fillna(x.mean()))
#Dropping all additional missing values
data = data.dropna()

#Splitting the data feature Route into origin, destination and transit if present
def clean_text(text):
    return re.sub(r'[^\w\s]', '', text) 

def split_route(route):
    parts = route.split(' to ', 1)

    if len(parts) < 2:
        return None, None, None
    Origin = clean_text(parts[0].strip())
    Destination = clean_text(parts[1].strip())

    if 'via' in Destination:
        Destination, Transit = Destination.split(' via ', 1)
        Transit = clean_text(Transit.strip())
    else:
        Transit = None
    return Origin, Destination, Transit

data[['Origin', 'Destination', 'Transit']] = data['Route'].apply(lambda x: pd.Series(split_route(x)))

#Dropping columns with no value for the intended purpose
data = data.drop(columns=['Unnamed: 0', 'Review_Title', 'Review Date', 'Verified', 'Route', 'Aircraft'])

#mapping abbreviations to full
abbreviation_to_full_name = {
    'LMT': 'Klamath Falls',
    'MTR': 'Montería',
    'NAP': 'Naples',
    'OR': 'Oregon',
    'BGW': 'Baghdad',
    'HYD': 'Hyderabad',
    'LBS': 'Labasa',
    'CGO': 'Zhengzhou',
    'CPT': 'Cape Town',
    'ALA': 'Alma Ata',
    'MNL': 'Manila',
    'HAM': 'Hamburg',
    'ORD': 'Chicago',
    'BGI': 'Bridgetown',
    'EUG': 'Eugene',
    'FLL': 'Fort Lauderdale',
    'MFM': 'Macau',
    'SZG': 'Salzburg',
    'RGN': 'Yangon (Rangoon)',
    'NY': 'New York City',
    'AMS': 'Amsterdam',
    'TVL': 'South Lake Tahoe',
    'MCT': 'Muscat',
    'TSN': 'Tianjin',
    'MLA': 'Valletta (Malta)',
    'HKG': 'Hong Kong',
    'MVR': 'Maroua',
    'DAL': 'Dallas',
    'WA': 'Wa',
    'EWN': 'New Bern',
    'PHL': 'Philadelphia',
    'BHX': 'Birmingham',
    'MUC': 'Munich',
    'VAR': 'Varna',
    'JUL': 'Juliaca',
    'MVD': 'Montevideo',
    'NAN': 'Nadi',
    'VFA': 'Victoria Falls',
    'PLZ': 'Port Elizabeth',
    'DLA': 'Douala',
    'DUS': 'Dusseldorf',
    'MEL': 'Melbourne',
    'BKK': 'Bangkok',
    'ALC': 'Alicante',
    'MRS': 'Marseille',
    'KIX': 'Osaka',
    'PER': 'Perth',
    'LHR': 'London Heathrow',
    'HIR': 'Honiara',
    'WI': 'Milwaukee',
    'CPH': 'Copenhagen',
    'SEA': 'Seattle',
    'JRT': 'Santorini',
    'MLE': 'Male',
    'CFU': 'Corfu',
    'PVR': 'Puerto Vallarta',
    'EZE': 'Buenos Aires',
    'LCY': 'London City',
    'CDG': 'Paris Charles de Gaulle',
    'GMP': 'Seoul',
    'TAS': 'Tashkent',
    'SDU': 'Rio de Janeiro',
    'PEN': 'Penang',
    'ROS': 'Rosario',
    'KWI': 'Kuwait City',
    'BOD': 'Bordeaux',
    'SZB': 'Kuala Lumpur',
    'GOI': 'Goa',
    'GUA': 'Guatemala City',
    'PVG': 'Shanghai-Pudong',
    'CMH': 'Columbus',
    'KUL': 'Kuala Lumpur',
    'MXP': 'Milan',
    'SJU': 'San Juan',
    'PKG': 'Lumut',
    'FAO': 'Faro',
    'PNG': 'Port Moresby',
    'EDI': 'Edinburgh',
    'COK': 'Cochin',
    'CMB': 'Colombo',
    'ORN': 'Oran',
    'LIM': 'Lima',
    'SCL': 'Santiago',
    'LJG': 'Lijiang',
    'BOS': 'Boston',
    'WEH': 'Weihai',
    'YUL': 'Montreal',
    'FCO': 'Rome',
    'DYG': 'Zhangjiajie',
    'PUJ': 'Punta Cana',
    'SOF': 'Sofia',
    'HAV': 'Havana',
    'LAD': 'Luanda',
    'FOZ': 'Foz do Iguaçu',
    'HEK': 'Heihe',
    'DAR': 'Dar Es Salaam',
    'MUM': 'Mumbai',
    'MSQ': 'Minsk',
    'DAD': 'Da Nang City',
    'PCL': 'Pucallpa',
    'GYE': 'Guayaquil',
    'SID': 'Sal',
    'LOS': 'Lagos',
    'OLB': 'Olbia',
    'ATQ': 'Amritsar',
    'GKA': 'Goroka',
    'MRU': 'Mauritius',
    'CEB': 'Cebu',
    'ISB': 'Islamabad',
    'TUN': 'Tunis',
    'CAN': 'Guangzhou',
    'KMG': 'Kunming',
    'BWI': 'Baltimore',
    'ASU': 'Asuncion',
    'WDH': 'Windhoek',
    'IKA': 'Tehran',
    'GOA': 'New York City',
    'KLO': 'San Francisco',
    'UUS': 'Los Angeles',
    'HEL': 'Helsinki',
    'SFB': 'Orlando Sanford',
    'NGO': 'Nagoya',
    'ACC': 'Accra',
    'RMF': 'Marsa Alam',
    'SVO': 'Moscow Sheremetyevo',
    'TBI': 'Tbilisi',
    'OOL': 'Gold Coast',
    'HAM': 'Hamburg',
    'PUQ': 'Punta Arenas',
    'MCO': 'Orlando',
    'ZRH': 'Zurich',
    'BGR': 'Bangor',
    'CNX': 'Chiang Mai',
    'IQT': 'Iquitos',
    'NBO': 'Nairobi',
    'REC': 'Recife',
    'DPS': 'Denpasar',
    'XMN': 'Xiamen',
    'CTU': 'Chengdu',
    'KGL': 'Kigali',
    'GYD': 'Baku',
    'SUV': 'Suva',
    'LAS': 'Las Vegas',
    'SVX': 'Yekaterinburg',
    'BSB': 'Brasilia',
    'HOG': 'Holguin',
    'MDQ': 'Mar del Plata',
    'KRK': 'Krakow',
    'OTP': 'Bucharest Otopeni',
    'TXL': 'Berlin Tegel',
    'POM': 'Port Moresby',
    'YYZ': 'Toronto',
    'LBV': 'Libreville',
    'HKT': 'Phuket',
    'BAQ': 'Barranquilla',
    'VKO': 'Moscow Vnukovo',
    'PMO': 'Palermo',
    'SSH': 'Sharm el-Sheikh',
    'BGA': 'Bucaramanga',
    'STN': 'London Stansted',
    'PEK': 'Beijing Capital',
    'PDG': 'Padang',
    'BLQ': 'Bologna',
    'CUS': 'Cusi',
    'LIN': 'Milan Linate',
    'LIS': 'Lisbon',
    'MDE': 'Medellín',
    'YEG': 'Edmonton',
    'REU': 'Reus',
    'SRT': 'Sao Tome',
    'JOG': 'Yogyakarta',
    'LBA': 'Leeds Bradford',
    'MAD': 'Madrid',
    'WUH': 'Wuhan',
    'USM': 'Koh Samui',
    'JFK': 'New York John F. Kennedy',
    'KEF': 'Reykjavik',
    'HOR': 'Khartoum',
    'MDL': 'Mandalay',
    'SYD': 'Sydney',
    'CT': 'Catania',
    'RUN': 'Saint-Denis',
    'DKR': 'Dakar',
    'CGK': 'Jakarta',
    'RNO': 'Reno',
    'ORY': 'Paris Orly',
    'MDC': 'Medellín',
    'NGB': 'Ningbo',
    'KBV': 'Krabi',
    'FRA': 'Frankfurt',
    'PDL': 'Ponta Delgada',
    'STR': 'Stuttgart',
    'CWB': 'Curitiba',
    'VCE': 'Venice',
    'LXA': 'Lhasa',
    'PRG': 'Prague',
    'FLN': 'Florianópolis',
    'SRG': 'Semarang',
    'HAN': 'Hanoi',
    'PBM': 'Georgetown',
    'VRA': 'Varadero',
    'DUR': 'Durban',
    'GRU': 'São Paulo',
    'DFW': 'Dallas Fort Worth',
    'DIL': 'Dili',
    'PRI': 'Puerto Rico',
    'CCU': 'Kolkata',
    'IPH': 'Ipoh',
    'AKL': 'Auckland',
    'BDO': 'Bandung',
    'DMK': 'Don Mueang',
    'HGH': 'Hangzhou',
    'SGN': 'Ho Chi Minh City',
    'JRO': 'Kilimanjaro',
    'LTN': 'London Luton',
    'OVB': 'Novosibirsk',
    'MSP': 'Minneapolis',
    'NYT': 'New York',
    'A': 'Athens',
    'CNS': 'Cairns',
    'DEL': 'Delhi',
    'VTE': 'Vientiane',
    'NOU': 'Noumea',
    'PTP': 'Pointe-à-Pitre',
    'BXBBWN': 'Brisbane',
    'LUX': 'Luxembourg',
    'BON': 'Bonaire',
    'ITM': 'Osaka Itami',
    'CUR': 'Curacao',
    'VIE': 'Vienna',
    'PPT': 'Papeete',
    'NRT': 'Narita',
    'GIG': 'Rio de Janeiro',
    'ACE': 'Lanzarote',
    'PDX': 'Portland',
    'IKT': 'Irkutsk',
    'SXF': 'Berlin Schönefeld',
    'TKG': 'Tanjung Karang',
    'FAE': 'Faroe Islands',
    'CUZ': 'Cusco',
    'YKS': 'Yakutsk',
    'SFG': 'San Francisco',
    'KOE': 'Koulamoutou',
    'BOG': 'Bogotá',
    'RNG': 'Rangoon',
    'POP': 'Puerto Plata',
    'BOM': 'Mumbai',
    'HND': 'Haneda',
    'SXM': 'Sint Maarten',
    'PFO': 'Paphos',
    'MIA': 'Miami',
    'HRE': 'Harare',
    'BOH': 'Bournemouth',
    'BIR': 'Birmingham',
    'GND': 'Grenada',
    'SDQ': 'Santo Domingo',
    'SCQ': 'Santiago de Compostela',
    'FNC': 'Funchal',
    'FRS': 'Fresno',
    'SUB': 'Surabaya',
    'KIV': 'Chisinau',
    'LYS': 'Lyon',
    'DMO': 'Damascus',
    'BLZ': 'Blantyre',
    'PVK': 'Preveza',
    'SCK': 'Stockton',
    'UBP': 'Uberlândia',
    'UKB': 'Kobe',
    'CMF': 'Chambery',
    'LAX': 'Los Angeles',
    'POS': 'Port of Spain',
    'ARI': 'Arica',
    'FL': 'Florence',
    'UTH': 'Utha',
    'AYT': 'Antalya',
    'CJC': 'Calama',
    'IXM': 'Madurai',
    'DXB': 'Dubai',
    'SHA': 'Shanghai Hongqiao',
    'GEO': 'Georgetown',
    'PLM': 'Palangkaraya',
    'HUY': 'Hull',
    'CA': 'Caracas',
    'GCI': 'Guernsey',
    'REP': 'Siem Reap',
    'SXR': 'Srinagar',
    'FPO': 'Freeport',
    'KHI': 'Karachi',
    'MKJP': 'Montego Bay',
    'ZTH': 'Zakynthos',
    'AUA': 'Aruba',
    'PMI': 'Palma de Mallorca',
    'PNH': 'Phnom Penh',
    'FOC': 'Fuzhou',
    'KCH': 'Kuching',
    'CWL': 'Cardiff',
    'NCL': 'Newcastle',
    'CHC': 'Christchurch',
    'DC': 'Washington DC',
    'ALG': 'Algiers',
    'JMK': 'Mykonos',
    'SFO': 'San Francisco',
    'KNO': 'Medan',
    'YVR': 'Vancouver',
    'BCN': 'Barcelona',
    'CTS': 'Chitose',
    'KKC': 'Khon Kaen',
    'CJB': 'Coimbatore',
    'YHM': 'Hamilton',
    'LPA': 'Gran Canaria',
    'MAO': 'Manaus',
    'PA': 'Panama City',
    'PMC': 'Puerto Montt',
    'GVA': 'Geneva',
    'HLP': 'Halim Perdanakusuma',
    'ABZ': 'Aberdeen',
    'CUN': 'Cancun',
    'SIN': 'Singapore',
    'CUC': 'Cúcuta',
    'FUE': 'Fuerteventura',
    'IGR': 'Iguazu',
    'IND': 'Indianapolis',
    'BKI': 'Kota Kinabalu',
    'LGW': 'London Gatwick',
    'SKG': 'Thessaloniki',
    'CRK': 'Clark',
    'TFS': 'Tenerife South',
    'ELP': 'El Paso',
    'SEZ': 'Seychelles',
    'UTP': 'Utapao',
    'OGG': 'Kahului',
    'NC': 'Nanning',
    'DLM': 'Dalaman',
    'UPB': 'Urubupunga',
    'SNW': 'Sanya',
    'CJJ': 'Cheongju',
    'OPO': 'Porto',
    'TSE': 'Astana',
    'BLR': 'Bangalore',
    'RIX': 'Riga',
    'VVO': 'Vladivostok',
    'KBR': 'Kota Bharu',
    'EMA': 'East Midlands',
    'CCC': 'Cuba',
    'KY': 'Kyiv',
    'CSX': 'Changsha',
    'LJU': 'Ljubljana',
    'IGU': 'Iguazu',
    'DVO': 'Davao',
    'CLT': 'Charlotte',
    'IAH': 'Houston',
    'SKP': 'Skopje',
    'VLC': 'Valencia',
    'PKU': 'Pekanbaru',
    'IST': 'Istanbul',
    'TPA': 'Tampa',
    'HCM': 'Ho Chi Minh City',
    'AUH': 'Abu Dhabi',
    'KUF': 'Samara',
    'LPQ': 'Luang Prabang',
    'CHI': 'Chicago',
    'REL': 'Aguascalientes',
    'CFG': 'Córdoba',
    'DAC': 'Dhaka',
    'CTG': 'Cartagena',
    'BNE': 'Brisbane',
    'USH': 'Ushuaia',
    'ZHR': 'Zurich',
    'VRN': 'Verona',
    'OKA': 'Okinawa',
    'KTM': 'Kathmandu'
}

#Mapping the Airport code to the city name from the dictionary
data['Origin'] = data['Origin'].map(abbreviation_to_full_name).fillna(data['Origin'])
data['Destination'] = data['Destination'].map(abbreviation_to_full_name).fillna(data['Destination'])

#Saving the updated data set
data.to_csv('Airline_review_with_cities.csv', index=False)

print('Data successfully saved to csv')